services:
  redis:
    image: redis:7
    container_name: redis
    expose:
      - "6379"

  mongodb:
    image: mongo:7
    container_name: mongodb
    expose:
      - "27017"

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    command: npm run dev
    working_dir: /app/apps/auth-service
    depends_on:
      - redis
    expose:
      - "3001"

  devicecontrol-service:
    build:
      context: .
      dockerfile: apps/devicecontrol-service/Dockerfile
    command: npm run dev
    working_dir: /app/apps/devicecontrol-service
    depends_on:
      - mongodb
    expose:
      - "3003"

  telemetry-service:
    build:
      context: .
      dockerfile: apps/telemetry-service/Dockerfile
    command: npm run dev
    working_dir: /app/apps/telemetry-service
    depends_on:
      - mongodb
    expose:
      - "3002"

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
    working_dir: /app/apps/gateway
    depends_on:
      - auth-service
      - devicecontrol-service
      - telemetry-service