apiVersion: 1

datasources:
  - name: k6-influx
    uid: k6-influx-db
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: ''
    jsonData:
      version: InfluxQL
      httpMode: GET
      dbName: k6
    isDefault: true
    editable: false
